FROM python:3.10

ENV PYTHONDONTWRITEBYTECOE 1
ENV PYTHONBUFFRED 1

RUN mkdir /app
WORKDIR /app

COPY requirements.txt requirements.txt

RUN apt-get update
RUN apt-get install -y gettext tzdata

RUN python -m pip install -r requirements.txt

COPY . .

ENTRYPOINT ["python","manage.py","runserver"]