version: "3.5"

services:
  redis_cache:
    restart: always
    image: redis:6.2

postgres_db:
  restart: always
  image: postgres:14
  environment:
    POSTGRES_USER:"postgres_db_user"
    POSTGRES_PASSWORD:"postgres_db_password"
    POSTGRES_DB:"postgres_db_database"
  ports:
    . "5432:5432"
  volumes:
    . pgdata:var/lib/postgresql/data

web:
  container_name: cowrk_backend
  environment:
  build:
    context: '.'
    dockerfile: ".DockerFile"
    